"""empty message

Revision ID: 3769b7d4548a
Revises: ec44780cd9d0
Create Date: 2026-09-27 18:41:55.084405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3769b7d4548a'
down_revision: Union[str, Sequence[str], None] = 'ec44780cd9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_like_user_service', 'likes', ['user_id', 'service_id'])
    op.alter_column('services', 'image_url', new_column_name='image_filename')
    op.alter_column('services', 'video_url', new_column_name='video_filename')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.alter_column('services', 'image_url', new_column_name='image_filename')
    op.alter_column('services', 'video_url', new_column_name='video_filename')
    op.drop_constraint('uq_like_user_service', 'likes', type_='unique')
    # ### end Alembic commands ###
